name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: miri
    - name: clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run miri tests
      run: MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test
